export const airlineFacts = {
  'vietnam-airlines': { founded: '1956', alliance: 'SkyTeam', history: 'Thành lập năm 1956, Vietnam Airlines là hãng hàng không quốc gia Việt Nam, gia nhập SkyTeam năm 2010 và được Skytrax công nhận 4 sao.' },
  'vietjet-air': { founded: '2007', alliance: 'Không thuộc liên minh lớn', history: 'Vietjet thành lập năm 2007, khai thác từ năm 2011 và là hãng hàng không tư nhân giá rẻ của Việt Nam.' },
  'eva-air': { founded: '1989', alliance: 'Star Alliance', history: 'EVA Air được thành lập tại Đài Loan năm 1989, khai thác chuyến bay đầu tiên năm 1991 và hiện là thành viên Star Alliance.' },
  'korean-air': { founded: '1969', alliance: 'SkyTeam', history: 'Thành lập năm 1969, Korean Air là thành viên sáng lập SkyTeam, duy trì mạng bay quốc tế cùng cam kết về an toàn và dịch vụ khách hàng.' },
  'all-nippon-airways': { founded: '1952', alliance: 'Star Alliance', history: 'Thành lập năm 1952, ANA phát triển từ hãng hàng không Nhật Bản, đặt an toàn làm ưu tiên và gia nhập Star Alliance năm 1999.' },
  'japan-airlines': { founded: '1951', alliance: 'Oneworld', history: 'Được thành lập năm 1951, Japan Airlines là hãng hàng không Nhật Bản gia nhập Oneworld năm 2007.' },
  'singapore-airlines': { founded: '1972', alliance: 'Star Alliance', history: 'Tách ra từ Malaysia-Singapore Airlines năm 1972, Singapore Airlines phát triển với định hướng đổi mới và đặt khách hàng làm trọng tâm.' },
  'cathay-pacific': { founded: '1946', alliance: 'Oneworld', history: 'Cathay Pacific thành lập năm 1946, phát triển từ một máy bay thành hãng hàng không quốc tế và là thành viên sáng lập Oneworld.' },
  'china-airlines': { founded: '1959', alliance: 'SkyTeam', history: 'Thành lập năm 1959, China Airlines là hãng hàng không Đài Loan thuộc SkyTeam và được APEX công nhận Five Star Global Airline.' },
  'starlux-airlines': { founded: '2018', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 2018, STARLUX là hãng hàng không Đài Loan khai thác chuyến bay từ 2020 và đạt xếp hạng 5 sao Skytrax năm 2025.' },
  'qatar-airways': { founded: '1993', alliance: 'Oneworld', history: 'Qatar Airways được thành lập năm 1993, là thành viên Oneworld và được Skytrax ghi nhận nhiều lần qua các giải thưởng hàng không.' },
  emirates: { founded: '1985', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 1985, Emirates phát triển từ hãng hàng không Dubai thành hãng quốc tế với mạng lưới điểm đến rộng khắp.' },
  'turkish-airlines': { founded: '1933', alliance: 'Star Alliance', history: 'Thành lập năm 1933, Turkish Airlines gia nhập Star Alliance năm 2008 và hiện được Skytrax xếp hạng hãng 4 sao.' },
  'bamboo-airways': { founded: '2017', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 2017, Bamboo Airways khai thác chuyến bay đầu tiên năm 2019 và là hãng hàng không tư nhân Việt Nam.' },
  'vietravel-airlines': { founded: '2019', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 2019, khai thác chuyến bay thương mại đầu tiên năm 2021 và nhận giải Hãng hàng không mới hàng đầu châu Á năm 2022.' },
  'asiana-airlines': { founded: '1988', alliance: 'Star Alliance', history: 'Thành lập năm 1988, Asiana Airlines gia nhập Star Alliance năm 2003 và nhấn mạnh an toàn cùng sự hài lòng của khách hàng.' },
  'peach-aviation': { founded: '2011', alliance: 'Không thuộc liên minh lớn', history: 'Peach Aviation thành lập năm 2011, là hãng hàng không giá rẻ Nhật Bản, đã phục vụ hơn 75 triệu hành khách.' },
  scoot: { founded: '2011', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập tháng 11 năm 2011, Scoot là hãng hàng không giá rẻ thuộc Singapore Airlines, chú trọng kết nối và trải nghiệm du lịch hiện đại.' },
  'hong-kong-airlines': { founded: '2006', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 2006, Hong Kong Airlines là hãng hàng không đầy đủ dịch vụ, được Skytrax duy trì xếp hạng bốn sao từ năm 2011.' },
  'hk-express': { founded: '2004', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 2004, HK Express là hãng hàng không giá rẻ thuộc Cathay Group, được ghi nhận về an toàn và đúng giờ.' },
  'thai-airways': { founded: '1960', alliance: 'Star Alliance', history: 'Thành lập năm 1960, Thai Airways là hãng hàng không quốc gia Thái Lan và là thành viên sáng lập Star Alliance năm 1997.' },
  'malaysia-airlines': { founded: '1937', alliance: 'Oneworld', history: 'Bắt nguồn từ Malayan Airways Limited thành lập năm 1937, Malaysia Airlines là hãng hàng không quốc gia Malaysia và thành viên Oneworld.' },
  airasia: { founded: '2001', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 2001, AirAsia là hãng hàng không giá rẻ khu vực, theo đuổi mục tiêu giúp việc bay trở nên dễ tiếp cận.' },
  'philippine-airlines': { founded: '1941', alliance: 'Oneworld', history: 'Thành lập năm 1941, Philippine Airlines là hãng hàng không quốc gia Philippines, hãng thương mại đầu tiên của châu Á.' },
  'cebu-pacific': { founded: '1988', alliance: 'Không thuộc liên minh lớn', history: 'Cebu Pacific được thành lập năm 1988, khai thác chuyến bay từ 1996 và duy trì chứng nhận an toàn IOSA theo thông tin công bố.' },
  'garuda-indonesia': { founded: '1949', alliance: 'SkyTeam', history: 'Thành lập năm 1949, Garuda Indonesia là hãng hàng không quốc gia Indonesia và gia nhập SkyTeam từ năm 2014.' },
  'batik-air-indonesia': { founded: '2013', alliance: 'Không thuộc liên minh lớn', history: 'Batik Air Indonesia là hãng hàng không đầy đủ dịch vụ thuộc Lion Air Group, bắt đầu khai thác từ tháng 5 năm 2013.' },
  'batik-air-malaysia': { founded: '2012', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 2012, hãng hoạt động từ tháng 3 năm 2013 với tên Malindo Air, sau đó đổi tên thành Batik Air Malaysia.' },
  'lion-air': { founded: '1999', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 1999, Lion Air là hãng hàng không giá rẻ nội địa lớn của Indonesia, khai thác chuyến bay đầu tiên năm 2000.' },
  'china-southern': { founded: '1988', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 1988, China Southern là hãng hàng không Trung Quốc có mạng bay rộng và được Skytrax xếp hạng bốn sao.' },
  'air-china': { founded: '1988', alliance: 'Star Alliance', history: 'Thành lập năm 1988, Air China là hãng hàng không quốc gia Trung Quốc và thành viên Star Alliance.' },
  'china-eastern': { founded: '1988', alliance: 'SkyTeam', history: 'Thành lập năm 1988, China Eastern là hãng hàng không lớn của Trung Quốc và thành viên SkyTeam.' },
  xiamenair: { founded: '1984', alliance: 'SkyTeam', history: 'Thành lập năm 1984, XiamenAir là hãng đầu tiên Trung Quốc vận hành theo mô hình doanh nghiệp hiện đại.' },
  'sichuan-airlines': { founded: '1986', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 1986, hãng nhấn mạnh an toàn và vận hành mạng bay nội địa, khu vực, quốc tế.' },
  'hainan-airlines': { founded: '1993', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 1993, Hainan Airlines duy trì hồ sơ khai thác an toàn và được Skytrax công nhận là hãng hàng không 5 sao nhiều năm.' },
  'shanghai-airlines': { founded: '1985', alliance: 'SkyTeam', history: 'Thành lập năm 1985, Shanghai Airlines là hãng thương mại đầu tiên của Trung Quốc có nhiều nguồn vốn.' },
  'air-macau': { founded: '1994', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 1994, Air Macau là hãng hàng không quốc gia của Macau, khai thác chủ yếu các điểm đến ở Bắc Á.' },
  'etihad-airways': { founded: '2003', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 2003, Etihad Airways là hãng hàng không quốc gia UAE, vận hành mạng bay quốc tế.' },
  'oman-air': { founded: '1993', alliance: 'Oneworld', history: 'Oman Air bắt đầu hoạt động năm 1993, phát triển thành hãng quốc tế lớn và được Oneworld ghi nhận với các sản phẩm, dịch vụ đạt giải.' },
  saudia: { founded: '1945', alliance: 'SkyTeam', history: 'Thành lập năm 1945, Saudia phục vụ hơn 100 điểm đến và tiếp tục hiện đại hóa đội bay theo hồ sơ của SkyTeam.' },
  'kuwait-airways': { founded: '1954', alliance: 'Không thuộc liên minh lớn', history: 'Kuwait Airways được thành lập năm 1954, là hãng hàng không quốc gia Kuwait và đã khôi phục hoạt động sau Chiến tranh Vùng Vịnh.' },
  'gulf-air': { founded: '1950', alliance: 'Không thuộc liên minh lớn', history: 'Là hãng hàng không quốc gia Bahrain, Gulf Air khai thác chuyến bay từ năm 1950 và duy trì mạng lưới quốc tế.' },
  'air-india': { founded: '1932', alliance: 'Star Alliance', history: 'Thành lập năm 1932 bởi JRD Tata, Air India là hãng hàng không quốc gia Ấn Độ và thành viên Star Alliance.' },
  indigo: { founded: '2006', alliance: 'Không thuộc liên minh lớn', history: 'IndiGo thành lập năm 2006, phát triển từ hãng hàng không nội địa Ấn Độ thành hãng quốc tế với mạng bay và đội tàu mở rộng.' },
  'srilankan-airlines': { founded: '1979', alliance: 'Oneworld', history: 'Ra mắt năm 1979, hãng hàng không quốc gia Sri Lanka gia nhập Oneworld năm 2014 và được giới thiệu với uy tín về dịch vụ.' },
  'ethiopian-airlines': { founded: '1945', alliance: 'Star Alliance', history: 'Thành lập năm 1945, Ethiopian Airlines bắt đầu khai thác năm 1946 và hiện là thành viên Star Alliance.' },
  'kenya-airways': { founded: '1977', alliance: 'SkyTeam', history: 'Thành lập năm 1977, Kenya Airways là hãng hàng không quốc gia Kenya và thành viên SkyTeam từ năm 2007.' },
  egyptair: { founded: '1932', alliance: 'Star Alliance', history: 'Thành lập năm 1932, EGYPTAIR được giới thiệu là một trong những hãng hàng không tiên phong và gia nhập Star Alliance năm 2008.' },
  lufthansa: { founded: '1926', alliance: 'Star Alliance', history: 'Thành lập năm 1926, Lufthansa trải qua nhiều giai đoạn lịch sử và phát triển thành hãng hàng không quốc tế có vị thế đáng kể.' },
  'air-france': { founded: '1933', alliance: 'SkyTeam', history: 'Air France thành lập năm 1933, gắn với lịch sử hàng không dân dụng và được ghi nhận về mạng lưới, an toàn, tiện nghi và dịch vụ.' },
  klm: { founded: '1919', alliance: 'SkyTeam', history: 'Thành lập năm 1919, KLM là hãng hàng không lâu đời nhất còn hoạt động dưới tên gốc và là thành viên sáng lập SkyTeam.' },
  'british-airways': { founded: '1974', alliance: 'Oneworld', history: 'British Airways thành lập năm 1974 từ sự hợp nhất BOAC và BEA, là thành viên sáng lập Oneworld.' },
  'swiss-international-air-lines': { founded: '2002', alliance: 'Star Alliance', history: 'Thành lập năm 2002, SWISS là hãng hàng không Thụy Sĩ thuộc Lufthansa Group và Star Alliance.' },
  'austrian-airlines': { founded: '1957', alliance: 'Star Alliance', history: 'Thành lập năm 1957, Austrian Airlines là hãng hàng không quốc gia Áo thuộc Lufthansa Group, thành viên Star Alliance.' },
  finnair: { founded: '1923', alliance: 'Oneworld', history: 'Thành lập năm 1923, Finnair là một trong những hãng hàng không hoạt động lâu đời nhất thế giới và gia nhập Oneworld năm 1999.' },
  'lot-polish-airlines': { founded: '1929', alliance: 'Star Alliance', history: 'Thành lập năm 1929, LOT Polish Airlines là một trong những hãng hàng không lâu đời nhất thế giới và gia nhập Star Alliance năm 2003.' },
  'united-airlines': { founded: '1926', alliance: 'Star Alliance', history: 'Có nguồn gốc từ Varney Air Lines năm 1926, United hoạt động với tên United Air Lines từ 1931.' },
  'american-airlines': { founded: '1930', alliance: 'Oneworld', history: 'American Airlines hình thành qua hợp nhất giai đoạn 1929–1930 và là thành viên sáng lập Oneworld.' },
  'air-canada': { founded: '1937', alliance: 'Star Alliance', history: 'Ra đời từ Trans-Canada Air Lines năm 1937, Air Canada là hãng hàng không quốc gia Canada và thành viên sáng lập Star Alliance.' },
  qantas: { founded: '1920', alliance: 'Oneworld', history: 'Thành lập năm 1920, Qantas là hãng hàng không Australia lâu đời và là thành viên sáng lập Oneworld.' },
  'jetstar-airways': { founded: '2003', alliance: 'Không thuộc liên minh lớn', history: 'Jetstar Airways là công ty con của Qantas, khai thác hàng không giá rẻ tại Australia và New Zealand từ năm 2004.' },
  'air-new-zealand': { founded: '1940', alliance: 'Star Alliance', history: 'Thành lập năm 1940, Air New Zealand là hãng hàng không quốc gia New Zealand và có xếp hạng tín nhiệm đầu tư Baa1 từ Moody’s.' },
  'delta-air-lines': { founded: '1925', alliance: 'SkyTeam', history: 'Delta Air Lines bắt nguồn từ hoạt động phun thuốc trừ sâu năm 1925, sau đó mở rộng quốc tế và là thành viên sáng lập SkyTeam.' },
  'alaska-airlines': { founded: '1932', alliance: 'Oneworld', history: 'Alaska Airlines bắt nguồn từ các hãng bay ở Anchorage năm 1932, đổi tên hiện nay năm 1944 và hiện là thành viên Oneworld.' },
  aeromexico: { founded: '1934', alliance: 'SkyTeam', history: 'Aeromexico thành lập năm 1934, là thành viên sáng lập SkyTeam và hãng hàng không quốc tế của Mexico.' },
  'air-mauritius': { founded: '1967', alliance: 'Không thuộc liên minh lớn', history: 'Thành lập năm 1967, Air Mauritius là hãng hàng không quốc gia Mauritius, duy trì kết nối quốc tế và đạt xếp hạng Skytrax 4 sao.' },
} as const;
