export type AirportRegion = 'Việt Nam' | 'Đông Á' | 'Đông Nam Á' | 'Nam Á' | 'Trung Đông & Châu Phi' | 'Châu Âu' | 'Châu Mỹ' | 'Châu Đại Dương';

export type AirportOption = { code: string; city: string; country: string; region: AirportRegion };

export const airportRegions: AirportRegion[] = ['Việt Nam', 'Đông Á', 'Đông Nam Á', 'Nam Á', 'Trung Đông & Châu Phi', 'Châu Âu', 'Châu Mỹ', 'Châu Đại Dương'];

export const airportOptions: AirportOption[] = [
  { code: 'SGN', city: 'TP. Hồ Chí Minh', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'HAN', city: 'Hà Nội', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'DAD', city: 'Đà Nẵng', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'CXR', city: 'Nha Trang', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'PQC', city: 'Phú Quốc', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'DLI', city: 'Đà Lạt', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'HUI', city: 'Huế', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'UIH', city: 'Quy Nhơn', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'HPH', city: 'Hải Phòng', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'VDO', city: 'Vân Đồn', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'VII', city: 'Vinh', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'THD', city: 'Thanh Hóa', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'VCL', city: 'Chu Lai', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'PXU', city: 'Pleiku', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'BMV', city: 'Buôn Ma Thuột', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'VCA', city: 'Cần Thơ', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'VKG', city: 'Rạch Giá', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'CAH', city: 'Cà Mau', country: 'Việt Nam', region: 'Việt Nam' }, { code: 'VCS', city: 'Côn Đảo', country: 'Việt Nam', region: 'Việt Nam' },
  { code: 'NRT', city: 'Tokyo Narita', country: 'Nhật Bản', region: 'Đông Á' }, { code: 'HND', city: 'Tokyo Haneda', country: 'Nhật Bản', region: 'Đông Á' }, { code: 'KIX', city: 'Osaka Kansai', country: 'Nhật Bản', region: 'Đông Á' }, { code: 'NGO', city: 'Nagoya', country: 'Nhật Bản', region: 'Đông Á' }, { code: 'FUK', city: 'Fukuoka', country: 'Nhật Bản', region: 'Đông Á' }, { code: 'ICN', city: 'Seoul Incheon', country: 'Hàn Quốc', region: 'Đông Á' }, { code: 'GMP', city: 'Seoul Gimpo', country: 'Hàn Quốc', region: 'Đông Á' }, { code: 'PEK', city: 'Bắc Kinh', country: 'Trung Quốc', region: 'Đông Á' }, { code: 'PVG', city: 'Thượng Hải Pudong', country: 'Trung Quốc', region: 'Đông Á' }, { code: 'CAN', city: 'Quảng Châu', country: 'Trung Quốc', region: 'Đông Á' }, { code: 'SZX', city: 'Thâm Quyến', country: 'Trung Quốc', region: 'Đông Á' }, { code: 'CTU', city: 'Thành Đô', country: 'Trung Quốc', region: 'Đông Á' }, { code: 'HKG', city: 'Hồng Kông', country: 'Hồng Kông', region: 'Đông Á' }, { code: 'TPE', city: 'Đài Bắc', country: 'Đài Loan', region: 'Đông Á' }, { code: 'KHH', city: 'Cao Hùng', country: 'Đài Loan', region: 'Đông Á' }, { code: 'MFM', city: 'Ma Cao', country: 'Ma Cao', region: 'Đông Á' },
  { code: 'SIN', city: 'Singapore', country: 'Singapore', region: 'Đông Nam Á' }, { code: 'BKK', city: 'Bangkok Suvarnabhumi', country: 'Thái Lan', region: 'Đông Nam Á' }, { code: 'DMK', city: 'Bangkok Don Mueang', country: 'Thái Lan', region: 'Đông Nam Á' }, { code: 'HKT', city: 'Phuket', country: 'Thái Lan', region: 'Đông Nam Á' }, { code: 'CNX', city: 'Chiang Mai', country: 'Thái Lan', region: 'Đông Nam Á' }, { code: 'KUL', city: 'Kuala Lumpur', country: 'Malaysia', region: 'Đông Nam Á' }, { code: 'PEN', city: 'Penang', country: 'Malaysia', region: 'Đông Nam Á' }, { code: 'CGK', city: 'Jakarta', country: 'Indonesia', region: 'Đông Nam Á' }, { code: 'DPS', city: 'Bali Denpasar', country: 'Indonesia', region: 'Đông Nam Á' }, { code: 'MNL', city: 'Manila', country: 'Philippines', region: 'Đông Nam Á' }, { code: 'CEB', city: 'Cebu', country: 'Philippines', region: 'Đông Nam Á' }, { code: 'PNH', city: 'Phnom Penh', country: 'Campuchia', region: 'Đông Nam Á' }, { code: 'REP', city: 'Siem Reap', country: 'Campuchia', region: 'Đông Nam Á' }, { code: 'VTE', city: 'Vientiane', country: 'Lào', region: 'Đông Nam Á' }, { code: 'RGN', city: 'Yangon', country: 'Myanmar', region: 'Đông Nam Á' },
  { code: 'DEL', city: 'Delhi', country: 'Ấn Độ', region: 'Nam Á' }, { code: 'BOM', city: 'Mumbai', country: 'Ấn Độ', region: 'Nam Á' }, { code: 'BLR', city: 'Bengaluru', country: 'Ấn Độ', region: 'Nam Á' }, { code: 'MAA', city: 'Chennai', country: 'Ấn Độ', region: 'Nam Á' }, { code: 'CCU', city: 'Kolkata', country: 'Ấn Độ', region: 'Nam Á' }, { code: 'DAC', city: 'Dhaka', country: 'Bangladesh', region: 'Nam Á' }, { code: 'CMB', city: 'Colombo', country: 'Sri Lanka', region: 'Nam Á' }, { code: 'KTM', city: 'Kathmandu', country: 'Nepal', region: 'Nam Á' },
  { code: 'DXB', city: 'Dubai', country: 'UAE', region: 'Trung Đông & Châu Phi' }, { code: 'AUH', city: 'Abu Dhabi', country: 'UAE', region: 'Trung Đông & Châu Phi' }, { code: 'DOH', city: 'Doha', country: 'Qatar', region: 'Trung Đông & Châu Phi' }, { code: 'IST', city: 'Istanbul', country: 'Thổ Nhĩ Kỳ', region: 'Trung Đông & Châu Phi' }, { code: 'SAW', city: 'Istanbul Sabiha', country: 'Thổ Nhĩ Kỳ', region: 'Trung Đông & Châu Phi' }, { code: 'RUH', city: 'Riyadh', country: 'Ả Rập Xê Út', region: 'Trung Đông & Châu Phi' }, { code: 'JED', city: 'Jeddah', country: 'Ả Rập Xê Út', region: 'Trung Đông & Châu Phi' }, { code: 'MCT', city: 'Muscat', country: 'Oman', region: 'Trung Đông & Châu Phi' }, { code: 'BAH', city: 'Bahrain', country: 'Bahrain', region: 'Trung Đông & Châu Phi' }, { code: 'KWI', city: 'Kuwait', country: 'Kuwait', region: 'Trung Đông & Châu Phi' }, { code: 'CAI', city: 'Cairo', country: 'Ai Cập', region: 'Trung Đông & Châu Phi' }, { code: 'ADD', city: 'Addis Ababa', country: 'Ethiopia', region: 'Trung Đông & Châu Phi' }, { code: 'NBO', city: 'Nairobi', country: 'Kenya', region: 'Trung Đông & Châu Phi' }, { code: 'JNB', city: 'Johannesburg', country: 'Nam Phi', region: 'Trung Đông & Châu Phi' },
  { code: 'LHR', city: 'London Heathrow', country: 'Anh', region: 'Châu Âu' }, { code: 'LGW', city: 'London Gatwick', country: 'Anh', region: 'Châu Âu' }, { code: 'CDG', city: 'Paris Charles de Gaulle', country: 'Pháp', region: 'Châu Âu' }, { code: 'ORY', city: 'Paris Orly', country: 'Pháp', region: 'Châu Âu' }, { code: 'FRA', city: 'Frankfurt', country: 'Đức', region: 'Châu Âu' }, { code: 'MUC', city: 'Munich', country: 'Đức', region: 'Châu Âu' }, { code: 'AMS', city: 'Amsterdam', country: 'Hà Lan', region: 'Châu Âu' }, { code: 'MAD', city: 'Madrid', country: 'Tây Ban Nha', region: 'Châu Âu' }, { code: 'BCN', city: 'Barcelona', country: 'Tây Ban Nha', region: 'Châu Âu' }, { code: 'FCO', city: 'Rome', country: 'Ý', region: 'Châu Âu' }, { code: 'MXP', city: 'Milan', country: 'Ý', region: 'Châu Âu' }, { code: 'ZRH', city: 'Zurich', country: 'Thụy Sĩ', region: 'Châu Âu' }, { code: 'VIE', city: 'Vienna', country: 'Áo', region: 'Châu Âu' }, { code: 'BRU', city: 'Brussels', country: 'Bỉ', region: 'Châu Âu' }, { code: 'CPH', city: 'Copenhagen', country: 'Đan Mạch', region: 'Châu Âu' }, { code: 'ARN', city: 'Stockholm', country: 'Thụy Điển', region: 'Châu Âu' }, { code: 'HEL', city: 'Helsinki', country: 'Phần Lan', region: 'Châu Âu' }, { code: 'OSL', city: 'Oslo', country: 'Na Uy', region: 'Châu Âu' }, { code: 'WAW', city: 'Warsaw', country: 'Ba Lan', region: 'Châu Âu' }, { code: 'PRG', city: 'Prague', country: 'Séc', region: 'Châu Âu' }, { code: 'BUD', city: 'Budapest', country: 'Hungary', region: 'Châu Âu' }, { code: 'ATH', city: 'Athens', country: 'Hy Lạp', region: 'Châu Âu' }, { code: 'DUB', city: 'Dublin', country: 'Ireland', region: 'Châu Âu' }, { code: 'LIS', city: 'Lisbon', country: 'Bồ Đào Nha', region: 'Châu Âu' },
  { code: 'JFK', city: 'New York JFK', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'EWR', city: 'Newark', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'LAX', city: 'Los Angeles', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'SFO', city: 'San Francisco', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'SEA', city: 'Seattle', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'ORD', city: 'Chicago', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'DFW', city: 'Dallas Fort Worth', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'IAH', city: 'Houston', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'ATL', city: 'Atlanta', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'MIA', city: 'Miami', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'IAD', city: 'Washington Dulles', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'BOS', city: 'Boston', country: 'Hoa Kỳ', region: 'Châu Mỹ' }, { code: 'YYZ', city: 'Toronto', country: 'Canada', region: 'Châu Mỹ' }, { code: 'YVR', city: 'Vancouver', country: 'Canada', region: 'Châu Mỹ' }, { code: 'YUL', city: 'Montreal', country: 'Canada', region: 'Châu Mỹ' }, { code: 'MEX', city: 'Mexico City', country: 'Mexico', region: 'Châu Mỹ' }, { code: 'GRU', city: 'São Paulo', country: 'Brazil', region: 'Châu Mỹ' }, { code: 'EZE', city: 'Buenos Aires', country: 'Argentina', region: 'Châu Mỹ' }, { code: 'SCL', city: 'Santiago', country: 'Chile', region: 'Châu Mỹ' }, { code: 'LIM', city: 'Lima', country: 'Peru', region: 'Châu Mỹ' },
  { code: 'SYD', city: 'Sydney', country: 'Úc', region: 'Châu Đại Dương' }, { code: 'MEL', city: 'Melbourne', country: 'Úc', region: 'Châu Đại Dương' }, { code: 'BNE', city: 'Brisbane', country: 'Úc', region: 'Châu Đại Dương' }, { code: 'PER', city: 'Perth', country: 'Úc', region: 'Châu Đại Dương' }, { code: 'ADL', city: 'Adelaide', country: 'Úc', region: 'Châu Đại Dương' }, { code: 'AKL', city: 'Auckland', country: 'New Zealand', region: 'Châu Đại Dương' }, { code: 'CHC', city: 'Christchurch', country: 'New Zealand', region: 'Châu Đại Dương' },
];

export function airportDisplay(airport: AirportOption) {
  return `${airport.city} (${airport.code})`;
}
