import Link from 'next/link';
import type { CSSProperties } from 'react';
import { BOOKING_URL, HOTLINE_PHONE, SUPPORT_PHONE, SUPPORT_PHONE_TEL, ZALO_SUPPORT_URL, toPublicAssetUrl, type LandingTheme, megaMenuGroups, navigation } from './content';
import { OfficeLocations } from './OfficeLocations';

const KVBK_LOGO_URL = toPublicAssetUrl('/manus-storage/khangvuongbooking-logo-optimized_beb3e0b1.webp');

function BrandLogo({ footer = false }: { footer?: boolean }) {
  return <img className="brand-logo" src={KVBK_LOGO_URL} alt="Khang Vuong Booking" width={560} height={102} decoding="async" loading={footer ? 'lazy' : 'eager'} fetchPriority={footer ? 'low' : 'high'} />;
}

export function SiteShell({ children, footerTheme, footerBackground }: { children: React.ReactNode; footerTheme?: LandingTheme; footerBackground?: string }) {
  const footerStyle = footerTheme ? { '--footer-primary': footerTheme.primary, '--footer-accent': footerTheme.accent, '--footer-background': footerBackground ? `url("${footerBackground}")` : 'none' } as CSSProperties : undefined;
  return <div className="site-shell">
    <div className="topline"><div className="frame"><span>Hành trình rõ ràng, hỗ trợ theo booking</span><div><a href="tel:19006695">{HOTLINE_PHONE}</a><a href={`tel:${SUPPORT_PHONE_TEL}`}>Gọi {SUPPORT_PHONE}</a><a href={ZALO_SUPPORT_URL} target="_blank" rel="noopener noreferrer">Zalo {SUPPORT_PHONE}</a><a href={BOOKING_URL} target="_blank" rel="noopener noreferrer">Kênh đặt vé chính thức</a></div></div></div>
    <header className="header"><div className="frame header-row"><Link href="/" className="brand" aria-label="Khang Vuong Booking"><BrandLogo /></Link><nav className="nav" aria-label="Điều hướng chính">{navigation.map(([slug, label]) => <Link href={`/${slug}`} key={slug}>{label}</Link>)}</nav><details className="mega-trigger"><summary>Danh mục <b>⌄</b></summary><div className="mega-panel"><div className="mega-grid">{megaMenuGroups.map((group) => <section key={group.title}><h2>{group.title}</h2><div>{group.items.map((item) => <Link key={item.slug} href={`/${item.slug}`}>{item.label}</Link>)}</div><Link className="mega-cta" href={`/${group.cta.slug}`}>{group.cta.label} →</Link></section>)}</div><section className="mega-support"><h2>Dịch vụ hỗ trợ hành khách theo hãng</h2><div><Link href="/ve-thu-cung">Vé thú cưng theo hãng</Link><Link href="/xe-lan">Xe lăn & hỗ trợ di chuyển</Link><Link href="/chon-cho">Chọn chỗ ngồi theo hãng</Link><Link href="/sua-ten-ve">Sửa tên vé theo hãng</Link><Link href="/nang-hang-ve">Nâng hạng vé theo hãng</Link><Link href="/ve-tu-nuoc-ngoai-ve-viet-nam">Vé từ nước ngoài về Việt Nam</Link></div></section></div></details><a className="header-action" href={BOOKING_URL} target="_blank" rel="noopener noreferrer">Đặt vé</a></div><details className="mobile-menu"><summary>Danh mục dịch vụ <b>+</b></summary><nav>{navigation.map(([slug, label]) => <Link href={`/${slug}`} key={slug}>{label}</Link>)}<Link href="/ve-du-hoc-sinh">Vé du học sinh</Link><Link href="/ve-tu-nuoc-ngoai-ve-viet-nam">Vé về Việt Nam</Link><Link href="/dich-vu-theo-hang">Dịch vụ theo hãng</Link></nav></details></header>
    {children}
    <footer className={`footer${footerTheme ? ' footer-airline' : ''}`} style={footerStyle}><div className="frame footer-grid"><div><Link href="/" className="brand brand-footer" aria-label="Khang Vuong Booking"><BrandLogo footer /></Link><p>Thông tin hành trình, dịch vụ và hướng dẫn giao dịch an toàn từ Khang Vuong Booking.</p></div><div><h2>Hành trình</h2><Link href="/ve-noi-dia">Vé máy bay nội địa</Link><Link href="/ve-may-bay/quoc-te">Vé máy bay quốc tế</Link><Link href="/ve-du-hoc-sinh">Vé du học sinh</Link><Link href="/ve-tu-nuoc-ngoai-ve-viet-nam">Vé từ nước ngoài về Việt Nam</Link><Link href="/hang-bay">Hãng hàng không</Link></div><div><h2>Dịch vụ</h2><Link href="/doi-ngay-ve">Đổi ngày vé</Link><Link href="/mua-them-hanh-ly">Mua thêm hành lý</Link><Link href="/sua-ten-ve">Sửa tên vé</Link><Link href="/nang-hang-ve">Nâng hạng vé</Link><Link href="/ve-thu-cung">Vé thú cưng</Link></div><div><h2>Hỗ trợ</h2><a href="tel:19006695">Gọi {HOTLINE_PHONE}</a><a href={`tel:${SUPPORT_PHONE_TEL}`}>Gọi {SUPPORT_PHONE}</a><a href={ZALO_SUPPORT_URL} target="_blank" rel="noopener noreferrer">Zalo {SUPPORT_PHONE}</a><a href="mailto:contact@khangvuongbooking.com">contact@khangvuongbooking.com</a><Link href="/lien-he">Liên hệ</Link><Link href="/ve-chung-toi">Về chúng tôi</Link><Link href="/canh-bao-an-toan">Cảnh báo an toàn giao dịch</Link></div></div><div className="frame"><OfficeLocations compact /></div><div className="frame footer-legal">© {new Date().getFullYear()} Khang Vuong Booking. Điều kiện vé và dịch vụ cần được xác nhận theo booking thực tế.</div></footer>
  </div>;
}
